#!/bin/bash

# This script is used to reload the server with the latest build of the project
# The project has to manually be built first before running this script (npm run build)

DIST_FOLDER=~/T26-Project-1/dist

if [ -d "$DIST_FOLDER" ]; then
    echo "Dist folder exists, proceeding with the reload."
    sudo rm -r /var/www/html/project1
    sudo mv "$DIST_FOLDER" /var/www/html/project1
    echo "Project has been successfully updated."
else
    echo "Error: The dist folder does not exist at $DIST_FOLDER. Please build the project first."
    exit 1
fi
